name: Benchmark

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubicloud-gpu-standard-1-latest
    strategy:
      matrix:
        index: [1, 2, 3, 4, 5, 6, 7, 8]
    name: runner ${{ matrix.index }}
    steps:
      - uses: actions/checkout@v4

      - name: nvidia-smi
        run: nvidia-smi

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Create /workspace/data directory
        run: mkdir -p ~/workspace/data

      - name: Run benchmark
        run: python basic_cpu_gpu_benchmark.py